name: Drata Remote

on:
  #push:
  #branches:
  #- '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # You fetch the current ref
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test

      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: reports/jest-*.xml # Path to test results
          reporter: jest-junit # Format of test results
